---
title: "Meeting Notes"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```



## Monday, January 22

- discussed our goals and courses (topics, students, etc.)

- plan to create apps to address ML topics (bias-variance trade-off)

- activities on data ethics (to be discussed later)

- Abhishek wanted to know about learnR tutorials (to be thought of later)

- activities related to ChatGPT, etc. (to be thought of later), Eric referred to Vimal



## Monday, January 29

- created GitHub repo

- discuss basic version of a couple of apps

- HAVE TO FIX the scale on flexibility

- discuss more such apps to address the concept of variance using multiple training datasets (compare linear models with LASSO, splines, etc. using boxplot of parameter estimates, with multiple scatterplots?)



## Monday, February 12

- scale on flexibility FIXED (on `Flex.R`)

- created a new app demonstrating bias and variance (`Bias_Variance.R`)

- PLANS: demonstrate KNN and single Decision Trees, Eric mentioned adding histograms of residuals, and add LASSO and ridge boxplots of parameter estimates

- two students might be working with Abhishek on these apps during Spring term

- idea about developing lesson plans associated with the apps (discussed in THIRD FLC meeting, see Google Drive folder)

- plan to have the apps ready before next Winter term

- will meet next week



## Monday, February 19

- Abhishek did not have time to work on the apps

- Eric updated the bias-variance app with histograms (at a different branch)

- We discussed possible variations - hollow histograms, density plots, etc. (TO DO)

- We talked about `Default` dataset from Intro to Stat Learning with R (James et al.) for first version of algorithmic bias study

- We talked about similar apps for Stat 2 level course developed by Keegan Kang (last FLC meeting)

- Found a similar app which can be used for reference (check associated article, and apps) [gursimar.github.io/d3-visualizations/bias-var/] 

- TO DO for Eric 

  - Put ML activities in GitHub folder and send to Abhishek 
  
  - Reach out to Colby at Wooster
  
  - Frame an idea of algorithmic bias
  
- TO DO for Abhishek

  - work on apps for KNN and trees 
  
  
  
  
## Monday, February 26

- Busy week/weekend for both of us, none of us could make any progress

- Will work on the TO DO lists from last meeting



## Monday, March 4

- Eric shared labs/activities on ML topics

- Eric has added more features to the bias-variance app

- Abhishek has a first basic version of KNN app, things to add - bias-variance plot, option for students to choose a different dataset, option to see a linear model, KNN classifier, etc. 

- TO DO for Abhishek - app with motivating ensemble trees

- discussed some initial ideas about algorithmic bias app - can we develop an app where students could set parameters and generate/download a dataset?

- next meeting in two weeks


## Tuesday, March 26

- our meetings have been rescheduled to Tuesday due to Abhishek's class prep on Mondays

- Eric discussed his ideas/outlines for the app on algorithmic bias, currently working on the data generation process

- Abhishek shared Shonda's app/activity on a similar topic (https://dataspace.sites.grinnell.edu/nypd1.html)



## Tuesday, April 2

- We discussed some of Eric's questions on the probability generating model for arrests, maybe a logistic regression (S-shaped) with interaction terms would work, Eric was initially thinking of probability depending on x (through x/(1+x)) where x depends on the variables

- Abhishek shared a couple of blog posts on Fair ML strategies (although they employ the `tidymodels` framework)

- Abhishek plans to work with his LU students in the coming weeks on the Bias-Variance app








